services:
  app:
    build: .
    container_name: itt_app
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./.env:/app/.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
